codecov:
  require_ci_to_pass: true
  notify:
    wait_for_ci: true
  branch: main

coverage:
  precision: 2
  round: down
  range: "80...100"
  
  status:
    project:
      default:
        target: auto
        threshold: 1%
        informational: false
    patch:
      default:
        target: auto
        threshold: 1%
        informational: false

# Fix paths from Docker container to actual paths
fixes:
  - "/app/::"

comment:
  layout: "reach,diff,flags,tree,footer"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true

ignore:
  - "tests/**/*"
  - "vendor/**/*"
  - "build/**/*"
  - "public/**/*"
  - "var/**/*"
  - "*.md"
